//package exception;
//
//public class ArrayExeptionTest {
//
//	public static void main(String[] args) {
//		// TODO Auto-generated method stub
//		
//		int[] arr = new int[5];
//	
//		// 예외처리를 위한 try catch 문
//		// try에서 Exception이 발생하면 catch문으로 넘어간다.
//		// catch문에서는 해당 예외에 대한 처리를 진행한다.
//		try {
//			for(int i=0; i<=5; i++) {
//				System.out.println(arr[i]);
//			}
//		}catch(ArrayIndexOutOfBoundsException e) {
//			System.out.println(e);
//			System.out.println("예외처리");
//		}
//			
//
//	}
//
//}
